baseURL = ''
languageCode = 'en-us'
paginate = 6
theme= "coHub"
title = 'STWFC'
 

  # Main Menu
  [[menu.Main]]
  name = "Our Club"
  url= "#gallery"
  weight = 1
  [[menu.Main]]
  name = "News and Updates"
  url= "#service"
  weight = 1
  [[menu.Main]]
  name = "Club History"
  url= "/about/"
  weight = 3
  [[menu.Main]]
  name = "Our Achievements"
  url= "#blog"
  weight = 4
  [[menu.Main]]
  name = "Player Profile"
  url= "#pricing"
  weight = 5
  [[menu.Main]]
  name = "FAQ"
  url= "#faq"
  weight = 6
  [[menu.Main]]
  name = "Contact Us"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  # theme_overrides = "css/overrides.css"
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = "© {year} <a href=\"https://staticmania.com/\" target=\"_blank\">StaticMania </a>"
  fabFormURL =  "https://fabform.io/f/u00kv3-"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/Club Logo.jpeg"
  footerlogo = "images/Club Logo.jpeg"
  footerDescription = "A great team surrounded by great people"

  [params.address]
  address = "Sunyani,P.O.Box SY1591"
  email = "sunyaniwisesfc33@gmail.com"
  openingDesc = "Give us a call or email us anytime, we endeavour to answer all enquiries within 24 hours"
  openingHours = "We are open from 7am — 7pm week days."
  phone = "+(49)17680773775 Or +(233)548553156"
         

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "45.4502528"
  longitude = "-122.783407"
  pinImage = "images/pin.png"

  # Social icons
  [[params.social]]
  icon = "ti-facebook"
  url = "https://www.facebook.com/"
  weight = 1
  [[params.social]]
  icon = "ti-twitter-alt"
  url = "https://twitter.com/"
  weight = 2
  [[params.social]]
  icon = "ti-dribbble"
  url = "https://dribbble.com/"
  weight = 3
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 4
  
  
